# Generated by Django 4.2.5 on 2023-09-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='obrazek_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elements.image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='obrazek_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.image'),
        ),
    ]
