# Generated by Django 4.2.5 on 2023-09-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_alter_catalog_obrazek_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='nazev',
            new_name='name',
        ),
    ]
