# Generated by Django 4.2.5 on 2023-09-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_rename_nazev_attributename_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='kod',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='attributename',
            old_name='zobrazit',
            new_name='show',
        ),
    ]
