# Generated by Django 4.2.5 on 2023-09-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_rename_kod_attributename_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='nazev_atributu_id',
            new_name='attribute_name',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='hodnota_atributu_id',
            new_name='attribute_value',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='hodnota',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='obrazek_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='obrazek',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cena',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mena',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nazev',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='obrazek_id',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='nazev',
            new_name='name',
        ),
    ]
