# Generated by Django 4.2.5 on 2023-09-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_rename_nazev_atributu_id_attribute_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elements.attributename'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_value',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elements.attributevalue'),
        ),
    ]
